[package]
name = "minotp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12"

[dev-dependencies]
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"

[features]

