[package]
name = "minotp"
version = "0.1.1"
edition = "2021"

description = "Dead simple OTP library for Rust."
authors = ["Charles Dong <charlesdong_2000@outlook.com>"]

license = "MIT OR Apache-2.0"

keywords = ["otp", "hotp", "totp", "password"]
categories = ["cryptography", "no-std"]

readme = "README.md"

repository = "https://github.com/chardon55/minotp.git"
homepage = "https://github.com/chardon55/minotp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12"

[dev-dependencies]
sha1 = { version = "0.10", default_features = false }
sha2 = { version = "0.10", default_features = false }
sha3 = { version = "0.10", default_features = false }

[features]

